version: '3'
services: 
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes: 
      - ./api:/usr/aspas/api
  database:
    container_name: aspas-database
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./docker/web/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ROOT_PASSWORD=secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: aspas-phpmyadmin
    links:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
