# Generated by Django 3.2 on 2021-04-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deaf',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='address.address')),
                ('phone', models.CharField(max_length=14)),
                ('cpf', models.IntegerField()),
                ('health_plan', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deafs',
            },
        ),
    ]
