# Generated by Django 3.2 on 2021-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deaf',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deaf',
            name='born_date',
        ),
        migrations.RemoveField(
            model_name='deaf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deaf',
            name='password',
        ),
        migrations.AddField(
            model_name='deaf',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
