# Generated by Django 3.2 on 2021-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deaf',
            name='cpf',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deaf',
            name='health_plan',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deaf',
            name='phone',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
