# Generated by Django 3.2.2 on 2021-05-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deaf',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
