# Generated by Django 3.2 on 2021-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0003_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='observations',
            field=models.TextField(null=True),
        ),
    ]
