# Generated by Django 3.2 on 2021-05-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0004_consult_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='modelity',
            field=models.IntegerField(choices=[(0, 'LOCAL'), (1, 'VIRTUAL')], default=0),
            preserve_default=False,
        ),
    ]
