# Generated by Django 3.2 on 2021-05-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0005_consult_modelity'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'AWAITING_INTERPRETER'), (2, 'SCHEDULED'), (3, 'FINISHED')], default=0),
            preserve_default=False,
        ),
    ]
