# Generated by Django 3.2 on 2021-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0006_consult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'AWAITING_INTERPRETER'), (2, 'SCHEDULED'), (3, 'FINISHED'), (4, 'FINISHED')]),
        ),
    ]
