# Generated by Django 3.2 on 2021-06-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
        ('surdo', '0007_alter_consult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='interpreter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interpreter.interpreter'),
        ),
    ]
