# Generated by Django 3.2.3 on 2021-06-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interpreter', '0001_initial'),
        ('surdo', '0009_consult_confirmed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'AWAITING_INTERPRETER'), (2, 'SCHEDULED'), (3, 'FINISHED'), (4, 'CANCELED')]),
        ),
        migrations.CreateModel(
            name='RejectedConsults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surdo.consult')),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interpreter.interpreter')),
            ],
            options={
                'db_table': 'reject_consults',
            },
        ),
    ]
