# Generated by Django 3.2 on 2021-06-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surdo', '0010_auto_20210610_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deaf',
            name='health_plan',
            field=models.CharField(max_length=255),
        ),
    ]
