# Generated by Django 3.2 on 2021-04-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_born_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'MAN'), (1, 'WOMAN'), (2, 'NOT_BINARY'), (3, 'OTHER')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'DEAF'), (1, 'INTERPRETER'), (2, 'HOSPITAL_STAFF')], default=3),
        ),
    ]
