# Generated by Django 3.2 on 2021-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born_date',
            field=models.DateField(null=True, verbose_name='born_date'),
        ),
    ]
